[github]
organisation_name = "ministryofjustice"

[activity_check]
inactivity_months = 18

[team.operations_engineering]
github_team = "operations-engineering"
slack_channel = "#operations-engineering-alerts"
remove_from_team = true
users_to_ignore = [ "cloud-platform-moj", "ScottSeaward" ]
repositories_to_ignore = [ "operations-engineering-reports" ]

# Add more teams here

