# This file is automatically generated via the Auth0 CLI.
# It can be safely removed after the successful generation
# of Terraform resource definition files.

import {
  id = "09bf7142-5047-4dbd-a142-cdbf9476e915"
  to = auth0_attack_protection.attack_protection
}

import {
  id = "afMYQcTUXSxVFBrFmHL4aanT6lkBbil5"
  to = auth0_client.default_app
}

import {
  id = "67v1ZXZuszSi8bQY9m4MIeSlUN4WMMeq"
  to = auth0_client.dockersso
}

import {
  id = "hrmwI3eZiyRLR2DQQmgCIZEPQ2wsuhxN"
  to = auth0_client.pagerduty
}

import {
  id = "RjmtgHdrzwJgJjT7FF6NpSF4oQ3YUc8N"
  to = auth0_client.api_explorer_application
}

import {
  id = "xXSrBtGQXB92MDyKwkTH6gDFGLcIHBR3"
  to = auth0_client.operations_engineering_standards_report
}

import {
  id = "Tyh7MbfR2GHeLxdx3pyEnt182xLMnKDP"
  to = auth0_client.prod_auth0managementapi
}

import {
  id = "FdLP0jvhj8qp8EltCjwU9se8emvQOYKW"
  to = auth0_client.moj_auth0_azure_prod
}

import {
  id = "4vI3vUJQ7ckzar9z2atQj45hPNRWG4TE"
  to = auth0_client.test_operations_engineering_moj_github_login
}

import {
  id = "qp6FwGllUikHXOn0dHMKIgF3dTWMCp9w"
  to = auth0_client.github_enterprise_cloud
}

import {
  id = "xrKMUJJxZaofhHo0foGwdnpLtcOxLeko"
  to = auth0_client.terraform_provider_auth0
}

import {
  id = "cb4ffae8-5a23-4eb4-ae0d-8cf7bf6d13c7"
  to = auth0_guardian.guardian
}

import {
  id = "6201546572dd0d003eb1a46b"
  to = auth0_resource_server.auth0_management_api
}

import {
  id = "c8d2390b-6f3b-48f8-a290-4e9dbbd769ce"
  to = auth0_tenant.tenant
}

