terraform state rm 'module.operations-engineering.github_actions_secret.default["TERRAFORM_AUTH0_S3_ROLE_ARN_DEV"]'
terraform state rm 'module.operations-engineering.github_actions_secret.default["TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_DEV"]'
terraform state rm 'module.operations-engineering.github_actions_secret.default["TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_PROD"]'


terraform state rm 'module.operations-engineering-example.github_actions_secret.default["DEV_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["DEV_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["DEV_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["DEV_KUBE_CLUSTER"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["PROD_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["PROD_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["PROD_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-example.github_actions_secret.default["PROD_KUBE_CLUSTER"]'

terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["DEV_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["DEV_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["DEV_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["PROD_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["PROD_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-join-github.github_actions_secret.default["PROD_KUBE_NAMESPACE"]'

terraform state rm 'module.operations-engineering-metadata-poc.github_actions_secret.default["DEV_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-metadata-poc.github_actions_secret.default["DEV_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-metadata-poc.github_actions_secret.default["DEV_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-metadata-poc.github_actions_secret.default["DEV_KUBE_CLUSTER"]'

terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["DEV_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["DEV_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["DEV_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["DEV_KUBE_CLUSTER"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["PROD_KUBE_TOKEN"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["PROD_KUBE_CERT"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["PROD_KUBE_NAMESPACE"]'
terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["PROD_KUBE_CLUSTER"]'