name: Archive repo if over a certain date

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1-5"

jobs:
  archive-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"
      - run: pip install -r scripts/python/requirements.txt
      - run: python scripts/python/archive-repositories.py
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.OPERATIONS_ENGINEERING }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
