name: "Auth0 Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/auth0/**.tf"
    branches:
      - main

env:
  TERRAFORM_VERSION: "1.6.6"

jobs:
  terraform:
    name: "Auth0 Terraform Plan"
    strategy:
      matrix:
        path:
          - "auth0/operations-engineering-test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AUTH0_S3_ROLE_ARN_DEV}}
          aws-region: eu-west-2

    - name: Terraform fmt
      id: fmt
      working-directory: terraform/${{ matrix.path }}
      run: terraform fmt -check -diff -recursive ./terraform
      continue-on-error: true

    - name: Terraform Init
      id: init
      working-directory: terraform/${{ matrix.path }}
      run: terraform init -input=false -no-color

    - name: Terraform Validate
      id: validate
      working-directory: terraform/${{ matrix.path }}
      run: terraform validate -input=false -no-color

    - name: Terraform Plan
      id: plan
      working-directory: terraform/${{ matrix.path }}
      run: terraform plan -input=false -no-color
      continue-on-error: true

    - name: Post Plan to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        allow-repeats: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ## ${{ matrix.path }} plan
          ```
          ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
          ```