name: Check for GitHub Anomalies

on:
  workflow_dispatch:

jobs:
  check-for-github-anomalies:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - run: python3 -m pip install -r requirements.txt
        - run: python3 -m bin.check_for_github_anomalies
          env:
            ADMIN_GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT_TOKEN }}
            ADMIN_SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}