# Need a GitHub Advanced Security license to run this action on private repos.

name: ♻️ Dependency Review
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths-ignore:
      - "source/**"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Dependency Review
        uses: actions/dependency-review-action@c74b580d73376b7750d3d2a50bfb8adc2c937507 # v3.1.5
        with:
          # Possible values: critical, high, moderate, low
          fail-on-severity: critical
