name: "Terraform for s3 to cloudtrail integration for github logs"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/log_streaming/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/log_streaming/**"
    branches: ["main"]

jobs:
  terraform-cloudtrail-streaming:
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      workflow_name: "s3-to-cloudtrail"
      path: "terraform/github/log_streaming"
      terraform_version: "1.6.6"
      name: "cloudtrail log streaming"
    secrets:
      iam_role: ${{ secrets.AWS_DSD_CICD_ADMIN_ROLE_ARN }}
      repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
