name: Delete AWS Route53 CNAME records

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1-12 *"

jobs:
  delete-cnames:
    runs-on: ubuntu-latest
    # These permissions are required to use AWS OIDC federate roles
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ID}}
          aws-region: eu-west-2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r python/requirements.txt
      - run: python -m python.scripts.delete_cnames
        env:
          HOSTED_ZONE_1: ${{ secrets.ROUTE53_HOSTEDZONE_ID_1 }}
          HOSTED_ZONE_2: ${{ secrets.ROUTE53_HOSTEDZONE_ID_2 }}
          LOGGING_LEVEL: ${{ secrets.LOGGING_LEVEL }}
