name: Delete AWS Route53 CNAME records

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1-12 *"

jobs:
  archive-repos:
    runs-on: ubuntu-latest
    # These permissions are required to use AWS OIDC federate roles
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{secrets.AWS_ID}}
          aws-region: eu-west-2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            architecture: 'x64'
            cache: 'pip'
      - run: pip install -r scripts/python/requirements.txt
      - run: python scripts/python/delete-cnames.py ${{ secrets.ROUTE53_HOSTEDZONE_ID_1 }} ${{ secrets.ROUTE53_HOSTEDZONE_ID_2 }}
