name: Dormant Users remove users

on:
  workflow_dispatch:
    inputs:
      organisation_name:
        type: choice
        description: Which Org?
        required: true
        options:
          - ministryofjustice
          - moj-analytical-services

jobs:
  remove-users:
    runs-on: ubuntu-latest
    # These permissions are required to use AWS OIDC federate roles
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_ID_DORMANT_USERS}}
          aws-region: eu-west-2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python3 -m pip install -r python/requirements.txt
      - run: python3 -m python.scripts.dormant_users ${{ github.event.inputs.organisation_name }} ${{ secrets.GH_BOT_PAT_TOKEN }} ${{ secrets.S3_BUCKET_NAME }} ${{ secrets.SLACK_BOT_TOKEN }} ${{ secrets.NOTIFY_PROD_API_KEY }} ${{ secrets.AUTH0_CLIENT_SECRET }} ${{ secrets.AUTH0_CLIENT_ID }} ${{ secrets.AUTH0_DOMAIN}} false false false true
        env:
          LOGGING_LEVEL: ${{ secrets.LOGGING_LEVEL }}
