name: 🧪 Experiment Get Collaborators GraphQL Query

on:
  workflow_dispatch:
  pull_request:

jobs:
  experiment-get-collaborators-graphql-query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install --dev
      - run: pipenv run python3 -m bin.remove_stale_outside_collaborators ${{ secrets.OPS_BOT_TOKEN }}
