name: 🧪 Experiment Check Workers CPU

on:

  pull_request:
  # Sequence of patterns matched against refs/heads
    branches:
    - main
  workflow_dispatch:


  jobs:
  check--runners-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Check CPU details
      run: |
        lscpu
