name: 🧪 Auto-merge Support Stats

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "data/**"

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check team membership and auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
          ORGANISATION: ministryofjustice
          TEAM: operations-engineering-support
        run: |
          # Check if the PR author is in the operations-engineering-support team
          if gh api orgs/$ORGANISATION/teams/$TEAM/memberships/${{ github.event.pull_request.user.login }} --silent; then
            echo "User is in the operations-engineering-support team. Proceeding with auto-merge."
            gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
          else
            echo "User is not in the operations-engineering-support team. Skipping auto-merge."
          fi
