name: Format code

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  format-code:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      files_changed: ${{ steps.formatter.outputs.files_changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: ministryofjustice/github-actions/code-formatter@ben-al-patch-1
        id: formatter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  run_tests:
    needs: format-code
    if: ${{ needs.format-code.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run tests if needed - Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

