name: Format code

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format-code:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v3
      - uses: ministryofjustice/github-actions/code-formatter@v13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
