name: Format code

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ministryofjustice/github-actions/code-formatter@v13
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT_TOKEN }}
