name: 🧑‍🔧 Dormant Users Debug Mode

on:
  workflow_dispatch:
    inputs:
      organisation_name:
        type: choice
        description: Which Org?
        required: true
        options:
          - ministryofjustice
          - moj-analytical-services
      step_one:
        type: choice
        description: Run send first email in debug mode
        required: true
        options:
          - true
          - false
      step_two:
        type: choice
        description: Run send reminder email in debug mode
        required: true
        options:
          - true
          - false
      step_three:
        type: choice
        description: Run remove users in debug mode
        required: true
        options:
          - true
          - false

jobs:
  debug-mode:
    runs-on: ubuntu-latest
    # These permissions are required to use AWS OIDC federate roles
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{secrets.AWS_ID_DORMANT_USERS}}
          aws-region: eu-west-2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python3 -m bin.dormant_users ${{ github.event.inputs.organisation_name }} ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }} ${{ secrets.S3_BUCKET_NAME }} ${{ secrets.SLACK_BOT_TOKEN }} ${{ secrets.NOTIFY_TEST_API_KEY }} ${{ secrets.AUTH0_CLIENT_SECRET }} ${{ secrets.AUTH0_CLIENT_ID }} ${{ secrets.AUTH0_DOMAIN}} true ${{ github.event.inputs.step_one }} ${{ github.event.inputs.step_two }} ${{ github.event.inputs.step_three }}
        env:
          LOGGING_LEVEL: "DEBUG"
