name: Alarm for Old POC Repositories

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SEND_TO_SLACK }}
  GH_TOKEN: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}

jobs:
  old-poc-repositories-alarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install

      - run: pipenv run python3 -m bin.alarm_for_old_poc_repositories

      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed: Alarm for Old POC Repositories"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
