name: 🤖 Alarm if a New GitHub Owner is Added

on:
  schedule:
    # Runs once a week on Monday at 1200
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  check-for-new-github-owners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python3 -m bin.check_for_new_github_owners
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.OPERATIONS_ENGINEERING_GITHUB_AUDIT_LOG_READ_ONLY}}
          ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SEND_TO_SLACK }}

      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed to check for new GitHub owners"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
