name: Certificate Expiry Undeliverable Report

on:
  schedule:
    - cron: '10 9 * * *'

jobs:
  certificate-expiry-check:
    name: Run certificate expiry undeliverable report script
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo content
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Python Setup
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'
      - name: Install Python Packages from Requirements File
        run: |
          pip install pipenv
          pipenv install
      - name: Execute certificate expiry undeliverable report run
        run: pipenv run python3 -m bin.report_certificate_expiry_undeliverable
        env:
          NOTIFY_PROD_API_KEY: ${{ secrets.NOTIFY_PROD_API_KEY }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2.5.0
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}