name: 🤖 Remove Collaborators Attached to Locked Repositories
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  remove-locked-repo-collaborators:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove collaborators attached to locked repositories
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python -m bin.remove_collaborator_locked_repos ${{ secrets.OPS_BOT_TOKEN }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
