name: Restore DSD Hosted Zones From S3 Backup 

on:
    pull_request:
    workflow_dispatch:
        inputs:
            hosted_zone_ids:
                description: "A comma separated string of hosted zone ids to restore e.g. 'id1,id2,id3', or 'all' to restore all hosted zones"
                required: true
                type: string

jobs:
  restore-from-backup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DSD_R53_RESTORE_FROM_BACKUP_ROLE_ARN }}
          aws-region: eu-west-2

      - run: python3 -m pip install -r requirements.txt
    #   - run: python3 -m bin.restore_route53_from_backup ${{inputs.hosted_zone_ids}}

    #   - name: Report failure to Slack
    #     if: always()
    #     uses: ravsamhq/notify-slack-action@v2
    #     with:
    #       status: ${{ job.status }}
    #       notify_when: "failure"
    #       notification_title: "Failed to backup Route 53"
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
