name: Alarm for new secret scanning alerts

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  detect-secret-scanning-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ministryofjustice/github-actions/slack-github-secret-scanning-integration@721b0f273fc8356611cb18b3dfc02074d59217da # v18.2.4
        with:
          github-token: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
