# This workflow is triggered manually to identify dormant GitHub users. It's currently in an experimental phase and will eventually be integrated into the main dormant user process.
name: 🧪 Identify Dormant GitHub Users

on:
  workflow_dispatch:
    inputs:
      days_since:
        type: choice
        description: "Select the number of days since to check for user dormancy."
        options:
          - "90"
          - "60"
          - "30"
        default: "90"
  schedule:
    - cron: "0 0 1 * *"

jobs:
  identify_dormant_github_users:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ministryofjustice/github-actions/setup-aws-profile@721b0f273fc8356611cb18b3dfc02074d59217da # v18.2.1
        with:
          role-arn: ${{secrets.AWS_GITHUB_DORMANT_USERS_ARN}}
          profile-name: auth0_logs_profile

      - name: Setup Profile to Query CloudTrail in Modernisation Platform Account `operations-engineering-dev`
        uses: ministryofjustice/github-actions/setup-aws-profile@721b0f273fc8356611cb18b3dfc02074d59217da # v18.2.1
        with:
          role-arn: ${{secrets.AWS_MP_OPERATIONS_ENGINEERING_DEV_QUERY_CLOUDTRAIL_ROLE_ARN}}
          profile-name: operations_engineering_dev_query_cloudtrail

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install

      - run: pipenv run python3 -m bin.identify_dormant_github_users_v2
        env:
          GH_MOJ_TOKEN: ${{ secrets.GH_MOJ_DORMANT_USERS_READ }}
          GH_MOJAS_TOKEN: ${{ secrets.GH_MOJAS_DORMANT_USERS_READ }}
          ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SEND_TO_SLACK }}
          DAYS_SINCE: ${{ inputs.days_since }}
