name: Move AS Org users to teams

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  as-org-move-users-to-teams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m bin.move_users_to_teams
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT_TOKEN }}
          ORG_NAME: "moj-analytical-services"
          CONFIG_FILE: "config/move-users-to-teams-as-org-config.yml"
          LOGGING_LEVEL: ${{ secrets.LOGGING_LEVEL }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
