name: Move all dependabot issues to "Refined and Ready"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 9 * * 1-5" # weekdays at 0915. Dependabot runs at 0900.

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python3 -m pip install -r python/requirements.txt
      - run: python3 -m python.scripts.move_dependabot_tickets --api_token ${{ secrets.ZENHUB_API_KEY }}
        env:
          LOGGING_LEVEL: ${{ secrets.LOGGING_LEVEL }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
