name: Remove users who have duplicated access to a repository

# Allows you to run this workflow manually from the Actions tab
on:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  remove-duplicated-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            architecture: 'x64'
            cache: 'pip'
      - run: python3 -m pip install -r scripts/python/requirements.txt
      - run: python3 scripts/python/remove-duplicated-repository-access.py ${{ secrets.OPERATIONS_ENGINEERING }} > output.txt
      - uses: actions/upload-artifact@v2
        with:
          path: output.txt
