name: "Test Excel Extraction"

on:
  workflow_dispatch:
  pull_request:


jobs:
    extract-data:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Import Excel Workbook
              run: curl -L -o DNS_Request_Form.xlsx "https://justiceuk-my.sharepoint.com/:x:/g/personal/lev_gorbunov_justice_gov_uk/EZHx882yal5LvlkLrTDNwicBsOeNcRLoBr7cWVUozdo_YQ"
            - uses: actions/setup-python@v5
              with:
                python-version: "3.11"
                cache: "pipenv"
            - name: Install Pipenv
              run: |
                pip install pipenv
                pipenv install
            - name: Extract and print Excel Workbook
              run: pipenv run python -m bin.print_excel_workbook
