name: URL Check

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  url-check:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact from publish.yml
        uses: actions/download-artifact@v3
        with:
          name: artifact.tar
      - name: Display structure of downloaded files
        run: |
          tar -xvf artifact.tar
          ls -R
          npm install linkinator
          npx linkinator ./docs --recurse --markdown
          echo "URL Check fails on private and internal GitHub repositories"
