name: URL Check

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  url-check:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: artifact.tar
    - name: Display structure of downloaded files
      run: ls -R